export const Goda = [
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 1 },
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 2 },
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 3 },
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 4 },
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 5 },
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 6 },
  { src: '../../../../../assets/gallery/weddings/main.webp', id: 7 },
];
export const Antanas = [
  { src: '../../../../assets/gallery/weddings/2.webp', id: 1 },
  { src: '../../../../assets/gallery/weddings/4.webp', id: 2 },
  { src: '../../../../assets/gallery/weddings/5.webp', id: 3 },
  { src: '../../../../assets/gallery/weddings/3.webp', id: 4 },
  { src: '../../../../assets/gallery/weddings/6.webp', id: 5 },
  { src: '../../../../assets/gallery/weddings/2.webp', id: 6 },
  { src: '../../../../assets/gallery/weddings/1.webp', id: 7 },
  { src: '../../../../assets/gallery/weddings/3.webp', id: 8 },
  { src: '../../../../assets/gallery/weddings/7.webp', id: 9 },
  { src: '../../../../assets/gallery/weddings/4.webp', id: 10 },
  { src: '../../../../assets/gallery/weddings/6.webp', id: 11 },
  { src: '../../../../assets/gallery/weddings/7.webp', id: 12 },
  { src: '../../../../assets/gallery/weddings/5.webp', id: 13 },
  { src: '../../../../assets/gallery/weddings/3.webp', id: 14 },
  { src: '../../../../assets/gallery/weddings/2.webp', id: 15 },
  { src: '../../../../assets/gallery/weddings/4.webp', id: 16 },
  { src: '../../../../assets/gallery/weddings/6.webp', id: 17 },
];
export const Gytis = [
  { src: '../../../../assets/gallery/weddings/2.webp', id: 2 },
  { src: '../../../../assets/gallery/weddings/1.webp', id: 3 },
  { src: '../../../../assets/gallery/weddings/4.webp', id: 1 },
  { src: '../../../../assets/gallery/weddings/3.webp', id: 5 },
  { src: '../../../../assets/gallery/weddings/6.webp', id: 4 },
  { src: '../../../../assets/gallery/weddings/5.webp', id: 6 },
  { src: '../../../../assets/gallery/weddings/7.webp', id: 7 },
  { src: '../../../../assets/gallery/weddings/2.webp', id: 2 },
  { src: '../../../../assets/gallery/weddings/1.webp', id: 3 },
  { src: '../../../../assets/gallery/weddings/4.webp', id: 1 },
  { src: '../../../../assets/gallery/weddings/3.webp', id: 5 },
  { src: '../../../../assets/gallery/weddings/6.webp', id: 4 },
  { src: '../../../../assets/gallery/weddings/5.webp', id: 6 },
  { src: '../../../../assets/gallery/weddings/7.webp', id: 7 },
  { src: '../../../../assets/gallery/weddings/2.webp', id: 2 },
  { src: '../../../../assets/gallery/weddings/1.webp', id: 3 },
  { src: '../../../../assets/gallery/weddings/4.webp', id: 1 },
  { src: '../../../../assets/gallery/weddings/3.webp', id: 5 },
  { src: '../../../../assets/gallery/weddings/6.webp', id: 4 },
  { src: '../../../../assets/gallery/weddings/5.webp', id: 6 },
  { src: '../../../../assets/gallery/weddings/7.webp', id: 7 },
];
// export const Goda = [
//   '../../../../../assets/gallery/weddings/main.webp',
//   '../../../../assets/gallery/weddings/1.webp',
//   '../../../../assets/gallery/weddings/2.webp',
//   '../../../../assets/gallery/weddings/3.webp',
//   '../../../../assets/gallery/weddings/4.webp',
//   '../../../../assets/gallery/weddings/5.webp',
//   '../../../../assets/gallery/weddings/6.webp',
//   '../../../../assets/gallery/weddings/7.webp',
// ];
// export const Antanas = [
//   '../../../../../assets/gallery/weddings/main.webp',
//   '../../../../assets/gallery/weddings/2.webp',
//   '../../../../assets/gallery/weddings/6.webp',
//   '../../../../assets/gallery/weddings/3.webp',
//   '../../../../assets/gallery/weddings/4.webp',
//   '../../../../assets/gallery/weddings/5.webp',
//   '../../../../assets/gallery/weddings/1.webp',
//   '../../../../assets/gallery/weddings/7.webp',
// ];
// export const Gytis = [
//   '../../../../assets/gallery/weddings/7.webp',
//   '../../../../../assets/gallery/weddings/main.webp',
//   '../../../../assets/gallery/weddings/2.webp',
//   '../../../../assets/gallery/weddings/6.webp',
//   '../../../../assets/gallery/weddings/3.webp',
//   '../../../../assets/gallery/weddings/4.webp',
//   '../../../../assets/gallery/weddings/1.webp',
//   '../../../../assets/gallery/weddings/5.webp',
// ];
